name: student_management
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  chopper: ^8.4.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.14
  intl: ^0.20.2
  animated_text_kit: ^4.2.3
  flutter_animate: ^4.5.2
  flutter_speed_dial: ^7.0.0
  drag_speed_dial: ^1.0.0
  badges: ^3.1.2
  bot_toast: ^4.1.3
  image_picker: ^0.8.4+4
  url_launcher: 6.3.0
  flutter_swipe_button: 2.1.3
  shimmer_animation: 2.2.1
  lottie: 3.1.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  audioplayers: 6.0.0
  custom_rating_bar: ^3.0.0
  intl_phone_field: ^3.1.0
  flutter_adaptive_layout: ^1.0.2
  pinput: ^5.0.0
  flutter_fgbg: ^0.3.0
  flutter_email_sender: ^6.0.3
  table_calendar: ^3.1.2
  pull_to_refresh_flutter3: ^2.0.2
  liquid_pull_to_refresh: ^3.0.1
  image_cropper: ^9.1.0
  crop_image: ^1.0.13
  multi_select_flutter: ^4.1.3
  image: ^4.2.0
  permission_handler: ^12.0.0+1
  csv: ^5.0.0
  path_provider: ^2.1.4
  http: ^1.2.2
  dio: ^5.7.0
  file_picker: ^8.1.5
  readmore: ^3.0.0
  flutter_slidable: ^3.1.2
  open_file: ^3.5.10
  change_app_package_name: ^1.4.0
  device_info_plus: ^11.1.1
  platform_detector: ^0.2.0
  map_launcher: ^3.5.0
  geocoding: ^3.0.0
  grouped_list: ^6.0.0
  timezone: ^0.10.0
  geolocator: 13.0.2
  fl_chart: 0.69.0
  flutter_local_notifications: ^18.0.1
  wakelock_plus: ^1.2.10
  shared_preferences: ^2.5.2
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.4
  hugeicons: ^0.0.11
  uuid: ^4.5.1
  flutter_custom_clippers: ^2.1.0
  path: ^1.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  chopper_generator: ^8.0.1
  device_preview: ^1.2.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/fonts/
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/clouds/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
